### ISSUE TITLE
Action to change box input in SuperSource

### ISSUE THREAD

**Issue by hjoelr** [bitfocus/companion-module-atem#15]
To start, let me just say Thank You for this module to Companion! It is a huge help to me! As I've been experimenting with this, I'm realizing that it would be very helpful to have an action to change a box input inside of SuperSource. I thought about adding it myself, but a cursory look at the code showed that it's a pretty sizeable module and would take quite a bit of my time just to understand how the current code even works. I was wondering if someone familiar with the code could add this functionality?

It's not outside the realm of possibility for me to attempt to add it, but I'd need some direction on how to set up a dev environment and the code layout of the extension.

Thanks!

**Comment by krocheck** [comment]
@hjoelr I'll take a look.  Yeah, it is a beefy module ... my fault mostly.  There's going to have to be a number of changes around SuperSource handling in the upstream library we use due to the new 8K switcher having 2 of them.  We're managing that implementation in a different branch, so I may be able to get this in the short term as-is.

**Comment by hjoelr** [comment]
@krocheck Wow, thanks for the quick response! I noticed that you're using [this library](https://github.com/nrkno/tv-automation-atem-connection) for most of the communications to the ATEM. They already have a function in there called [setSuperSourceBoxSettings](https://github.com/nrkno/tv-automation-atem-connection/blob/master/src/atem.ts#L320-L325) that may make it pretty simple to add to this library as is. My JS/TypeScript knowledge is shallow, but if I'm reading it right it seems that you can't set just the `source` property but have to set all the others (`enabled`, `x`, `y`, `size`, `cropped`, etc.) at the same time. Right now all I need/want is to change just the `source` property but leave all the others as they are.

**Comment by krocheck** [comment]
Yes, that is correct.  All of that data is reported from the atem, it just has to be stored in the states array.  Its one of my complaints for that library because technically speaking the atem protocol allows you to set flags for which variables are going to be updated, but atem-connection doesn't let you manipulate that such that every variable must be sent (even those not changing).

I think I got it close, but I won't be able to test.  Will you be in a position to test in the next few days?

**Comment by krocheck** [comment]
@hjoelr should be there for you in the current build.  I'll mostly be curious that it behaves correctly in terms of not changing the other parameters of the boxes.

**Comment by hjoelr** [comment]
@krocheck Thank you for the quick turnaround and implementation! Very grateful for your help 😊. I'll see if I can give it a try in the next day or two. The ATEM is at a different location than where I'm at, so I have to go there to test it.

**Comment by Julusian** [comment]
@krocheck The library should let you set just one of the box properties at a time (hence the Partial<SuperSourceBox> parameter type). It determines which properties to update based on what fields are set in the object parameter. If it is resetting the other properties at the same time then that is a bug

**Comment by krocheck** [comment]
@Julusian I'll have to test.  I feel like I experienced the opposite elsewhere but it was a ways back.

**Comment by baltedewit** [comment]
> I feel like I experienced the opposite elsewhere but it was a ways back.

That is strange, it is something that is used in almost all high level commands actually. Next time you see it, it would be great if you could open an issue in the repository with a report of which commands you were using. Regarding the supersource command, I can confirm the Partial object will work as it is used in production by the [Atem Compositor](https://github.com/TipoftheHats/atem-compositor/blob/76bef153e9dd39c7409919fba149414eb625e43b/app/client/elements/atem-supersource-box.js) project.

I've tried to use Companion to set the supersource boxes on a production over the weekend but it resets all other parameters to 0 currently, probably because it is missing state info about the boxes. It should work more reliably if you use a Partial object instead.

**Comment by krocheck** [comment]
Yeah, I need to get my atem over from the warehouse as per usual.  Since this is all still alpha/beta I'll get it cleaned up.  Is there polling we need to do to specifically?  I was under the impression all of the commands report out state on connection, so I was expecting SuperSourceBoxPropertiesCommand to report those states?  All things I can play with once a a unit is here.

**Comment by baltedewit** [comment]
Yup, should work the same. I'm just speculating as to why it might not work to be honest. I don't have a 2 M/E over here either, just happened to be using it for a production. (Routing the MV windows from streamdeck is awesome btw)

**Comment by krocheck** [comment]
Yeah, I was fairly infuriated when I couldn't do MV window changes in macros.  Some guys will put temporary changes on a latched button.  Definitely my favorite contribution to the project.  Happy others agree!

**Comment by baltedewit** [comment]
> I've tried to use Companion to set the supersource boxes on a production over the weekend but it resets all other parameters to 0 currently

Come to think about this again, I have no idea on what version of the firmware that atem was. If it was on 8.0 I guess we wouldn't expect the current commands to function correctly.
