### ISSUE TITLE
ATEM DSK Toggle

### ISSUE THREAD

**Issue by mambafiber** [bitfocus/companion-module-atem#25]
The DSK toggle appears to turn on DSK, but subsequent presses will not turn the DSK off. You can manually turn off DSK in ATEM software, or with a separate "OFF" key in companion. Do I understand the function corretcly? One press should turn it on, second press should turn it off-correct? Would also be nice to toggle the DSK auto instead of the cut in the same way...

Also, feedback appears to not work, key background doesn't change when DSK is on-air.

ATEM 1M/E 4k, v6.9, companion v 1.2.0-85393af-1109

**Comment by krocheck** [comment]
So there is complicated stuff going on in the background that we're working on addressing, specifically we're not (mostly because our upstream library) is not setup well to handle the changes in the different versions of the ATEM software.  For instance, I know in v8.0.1 based on the SDK readme that there we changes to DSK auto transition calls and some other DSK related things.  I suspect that's why this isn't working as you've reported.  Similarly to the OP running v6.9, I know the library was optimized for v7.2, however ran through v7.5.2 without issues that we know of.

The simple answer right now is that v8+ of ATEM is not supported and we're working on it, but its complicated because we don't want to break everyone else running v7.x who is happy as a clam.

**Comment by Julusian** [comment]
I can confirm that 8.0.1 broke the DSK auto command, so this not working is expected for now
