### ISSUE TITLE
[BUG] It is not possible to define which ME to get instance feedback from

### ISSUE THREAD

**Issue by twentyfiveframes** [bitfocus/companion-module-atem#45]
When configuring instance feedback in Companion version 1.4, it was possible to pick between the two ME's, but in version 2.0 (alpha/beta) you can only pick camera input, and the feedback is activated if either ME has the camera input in preview/program. 

**Screenshot from Companion 1.4, where it's working as expected**
<img width="907" alt="Screenshot 2020-01-27 at 23 31 29" src="https://user-images.githubusercontent.com/39236254/73220532-f3b9e900-415e-11ea-8684-6a0c928b1ed2.png">

Screenshot from Companion 2.0, where it's not possible to pick ME
<img width="895" alt="Screenshot 2020-01-27 at 23 31 25" src="https://user-images.githubusercontent.com/39236254/73220562-03d1c880-415f-11ea-825e-cff60d492a10.png">

**Comment by Julusian** [comment]
In 2.0 you have selected the new tally feedback mode (which follows what you will see on the multiviewer), rather than the program source feedback (only checks program of a single me) that was previously existed. note the name has tally at the end.
Have another look in the list for one with the exact name as before which should behave as you expect.

I did not realise they were named so similarly, that will be improved soon

**Comment by Julusian** [comment]
This should be clearer in latest 2.0
